version: '3'

services:
  redis:
    image: redis:latest
    ports: 
    - "6379:6379"
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: on-failure

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure

  celery:
    build: .
    command: celery -A restapi worker -B -l info 
    volumes: 
      - .:/code/
    links:
      - redis
    depends_on:
      - db
      - web

